# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy

on:
  push:
    branches:
      - merge-deployment-jobs
  workflow_dispatch:

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build:azure

      - name: Upload artifact for test/deploy jobs
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./dist/browser

  test:
    name: Run Unit and E2E Tests
    runs-on: ubuntu-latest
    needs: build  # ensures this runs after build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./dist/browser

      - name: Install dependencies
        run: npm ci

      - name: Run headless tests
        run: |
          npm run test:headless
          npm run e2e:headless

  deploy-azure:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure game-store-angular'
        id: deploy-to-game1
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'game-store-angular'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6D3CF3B69E8A4BBE85B5CC353EA6FF4E }}
          clean: true

      - name: 'Deploy to Azure game-store-angular3'
        id: deploy-to-game3
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'game-store-angular3'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9C1983EBE143426C99098E83CC8CBEC0 }}
          clean: true

  deploy-github-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration pages --base-href "https://jojozhuang.github.io/game-store-angular/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/browser