# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy

on:
  push:
    branches:
      - fix-page-refres-not-found
  workflow_dispatch:

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build:azure

      - name: Upload artifact for test/deploy jobs
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./dist/browser # package all files in dist/browser and name the artifact "node-app"

  test:
    name: Run Unit and E2E Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:headless

      - name: Run e2e tests
        run: npm run e2e:headless

  deploy-azure-game-store:
    name: Deploy to Azure game-1
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app # download the artifact and extract to the current working directory

      - name: Deploy to Azure game-store-angular
        id: deploy-to-game1
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'game-store-angular'
          slot-name: 'Production'
          package: . # deploy with all files in the current working directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6D3CF3B69E8A4BBE85B5CC353EA6FF4E }}
          clean: true

  deploy-azure-game-store3:
    name: Deploy to Azure game-3
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app # download the artifact and extract to the current working directory

      - name: Deploy to Azure game-store-angular3
        id: deploy-to-game3
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'game-store-angular3'
          slot-name: 'Production'
          package: . # deploy with all files in the current working directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9C1983EBE143426C99098E83CC8CBEC0 }}
          clean: true

  deploy-github-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4 # checkout all files to get access to GitHub Pages config

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./dist/browser # download the artifact to dist/browser

      - name: Adjust base href for GitHub Pages
        run: |
          sed -i 's|<base href="/">|<base href="/game-store-angular/">|' ./dist/browser/index.html

      - name: List files to be deployed
        run: ls -la # list all files in root directory for debugging

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/browser # deploy with all files in dist/browser
          clean: true
